package com.mantis.common.enums;

public enum EPermission {
    CREATE_USER,
    DELETE_USER,
    UPDATE_USER,
    CREATE_ROLE,
    DELETE_ROLE,
    UPDATE_ROLE,
    CREATE_PERMISSION,
    CREATE_GARAGE,
    DELETE_GARAGE,
    CREATE_DUTY,
    CREATE_REPAIR_SHOP,
    CREATE_REPAIR_SHOP_DUTY,
    CREATE_SHOP,
    CREATE_PRODUCT,
    CREATE_PRODUCT_SHOP_RELATION,

}
